# Rear lift

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 0, 0]
duration = 7

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 0, 0]
duration = 7

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 0, 0]
duration = 7

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 0, 0]
duration = 7

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 0, 0]
duration = 7

[[section]]
contact  = [1, 1, 1, 1]
duration = 9

[[section]]
contact  = [1, 1, 0, 0]
duration = 7

[[section]]
contact  = [1, 1, 1, 1]
duration = 9
