# FR Lift

# 1
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# 2
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# 3
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# 4
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# 5
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# 6
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# 7
[[section]]
contact  = [1, 1, 1, 1]
duration = 11

[[section]]
contact  = [0, 1, 1, 1]
duration = 7

# End
[[section]]
contact  = [1, 1, 1, 1]
duration = 11