# Walk wave

# Beginning of walk wave #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200

# Walk wave

[[step]]
type         = "locomotion"
vel_des      = [0.0, -0.0, 0.0]
omni         = 0
gait_id      = 60
duration     = 1000

[[step]]
type         = "locomotion"
vel_des      = [0.05, -0.0, 0.0]
omni         = 0
gait_id      = 60
duration     = 1000

[[step]]
type         = "locomotion"
vel_des      = [0.15, -0.0, 0.0]
omni         = 0
gait_id      = 60
duration     = 5640

[[step]]
type         = "locomotion"
vel_des      = [0.0, -0.0, 0.0]
omni         = 0
gait_id      = 60
duration     = 1000

# End of walk wave #

# Stand

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 500

[[step]]
type         = "transition"
height       = 0.24
duration     = 500

