# Ballet

# Beginning of ballet #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200

# Transition trotting

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 69
duration     = 600

# Ballet

[[step]]
type         = "locomotion"
vel_des      = [0.0, -0.025, 0.3]
omni         = 0
gait_id      = 68
duration     = 6000

# Transition trotting

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 69
duration     = 600

# End of ballet #

# Stand

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 500

[[step]]
type         = "transition"
height       = 0.24
duration     = 500
