
[[step]]
type         = "recoverystand"
duration     = 500

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, -0.12]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.12]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, -0.12]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.12]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, -0.12]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.12]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "recoverystand"
duration     = 500