
[[step]]
type         = "transition"
height       = 0.225
duration     = 200

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.15, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 108


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.03, -0.003, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0285, -0.009, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02625, -0.01425, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02325, -0.0195, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.01875, -0.02325, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0135, -0.027, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.00825, -0.0285, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.00225, -0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.00375, -0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.00975, -0.0285, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.015, -0.0255, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02025, -0.0225, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.024, -0.018, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.027, -0.01275, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02925, -0.0075, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.03, -0.0015, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02925, 0.0045, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02775, 0.0105, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0255, 0.01575, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02175, 0.02025, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.01725, 0.02475, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.012, 0.02775, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.006, 0.02925, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.00525, 0.02925, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.01125, 0.02775, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0165, 0.02475, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.021, 0.021, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02475, 0.0165, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02775, 0.01125, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02925, 0.00525, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.01275, 0.00075, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 208


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 108


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.03, -0.003, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0285, -0.009, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02625, -0.01425, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02325, -0.0195, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.01875, -0.02325, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0135, -0.027, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.00825, -0.0285, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.00225, -0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.00375, -0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.00975, -0.0285, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.015, -0.0255, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02025, -0.0225, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.024, -0.018, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.027, -0.01275, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02925, -0.0075, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.03, -0.0015, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02925, 0.0045, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02775, 0.0105, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0255, 0.01575, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02175, 0.02025, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.01725, 0.02475, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.012, 0.02775, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.006, 0.02925, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.00525, 0.02925, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.01125, 0.02775, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0165, 0.02475, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.021, 0.021, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02475, 0.0165, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02775, 0.01125, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02925, 0.00525, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.012, 0.00075, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.15, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.15, 0.0, 0.0]
duration     = 208

[[step]]
type         = "transition"
height       = 0.225
duration     = 500
