# Pitch down right

# Beginning of pitch down right #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.08, 0.03, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 1000


[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 71
duration     = 4320

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.04, -0.015, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 800

# End of pitch down right #

# Stand

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 500

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 500
