#	option1:
#		locomotion
#		xdot,ydot,yawdot
#		omni
#		gait
#		duration
#
#	option2:
#		pose
#		contact state
#		pose_body_cmd
#		pose_foot_cmd
#		pose_ctrl_point
#		duration
#	option3:
#		jump
#		jump_foot_support
#		jump_x_acc_cmd
#		jump_w_acc_cmd	
#		duration
#	option4:
#		transition
#		height
#		duration

# position ctrl: sit down and swing RF leg

[[step]]
type         = "transition"
height       = 0.25
duration     = 200

######
[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.3, 0.0, 0.05, -0.0, -0.05]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 600

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.0, 0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

######
[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.6, 0.0, -0.09, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 600


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.25, 0.0, -0.0, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.5, 0.0, -0.0, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.25, 0.0, -0.0, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.0, 0.04, -0.0, 0.05]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "transition"
height       = 0.25
duration     = 600