[[step]]
type         = "transition"
height       = 0.25
duration     = 500

# Beginning of front lift #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.095, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 1098

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, -0.03, 0.0,  0.0, 0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, 0.03, 0.0,  0.0, -0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, -0.03, 0.0,  0.0, 0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, 0.03, 0.0,  0.0, -0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, -0.03, 0.0,  0.0, 0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.05, -0.00, 0.0,  0.05, 0.00, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 750

# Stand

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.095, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 1000

# End of front lift #


# Beginning of trot in out #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200

# Trot in out

[[step]]
type         = "locomotion"
vel_des      = [0.0, -0.0, 0.0]
omni         = 0
gait_id      = 56
duration     = 2970

# # Stand

# [[step]]
# type         = "torctrlposture"
# foot_support = [1.0, 1.0, 1.0, 1.0]
# body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# foot_pose    = [0.0, 0.0, 0.0]
# duration     = 500

# End of trot in out #

# Stand

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 500

[[step]]
type         = "recoverystand"
duration     = 1000

# RecoveryStand

[[step]]
type         = "recoverystand"
duration     = 300


# Beginning of trot pitch #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200

# Trot pitch

[[step]]
type         = "locomotion"
vel_des      = [0.0, -0.0, 0.0]
omni         = 0
gait_id      = 57
duration     = 2970

# # Stand

# Beginning of ballet #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200

# Transition trotting

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 69
duration     = 600

# Ballet

[[step]]
type         = "locomotion"
vel_des      = [0.0, -0.025, 0.3]
omni         = 0
gait_id      = 68
duration     = 6000

# Transition trotting

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 69
duration     = 600

# End of ballet #


# PRONK        = 2,
# BOUND        = 7,


[[step]]
type         = "locomotion"
vel_des      = [0.1, 0.0, 0.0]
omni         = 0
gait_id      = 7
duration     = 1500

# [[step]]
# type         = "torctrlposture"
# foot_support = [1.0, 1.0, 1.0, 1.0]
# body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# foot_pose    = [0.0, 0.0, 0.0]
# duration     = 500

# End of trot pitch #


# Stand

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 500

# Beginning of sit-down #
[[step]]
type         = "transition"
height       = 0.225
duration     = 222

###### sit down
[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.45, 0.0, -0.05, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 444

###### shake body
[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.2, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 222


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.0, 0.0, -0.4, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 444


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.2, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 222

###### hold on a moment
[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.08, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 444