# Trot In Out

# Beginning of Trot In Out #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 500

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.04, -0.03, 0.0,  0.04, 0.03, 0.0,  -0.04, -0.03, 0.0,  -0.04, 0.03, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 1080

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.035]
landing_pos_des = [-0.02, 0.035, 0.0,  -0.02, -0.035, 0.0,  0.02, 0.035, 0.0,  0.02, -0.035, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 1080

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.04, -0.03, 0.0,  0.04, 0.03, 0.0,  -0.04, -0.03, 0.0,  -0.04, 0.03, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 1080

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.035]
landing_pos_des = [-0.02, 0.035, 0.0,  -0.02, -0.035, 0.0,  0.02, 0.035, 0.0,  0.02, -0.035, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 1080

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.00]
landing_pos_des = [0.04, -0.03, 0.0,  0.04, 0.03, 0.0,  -0.04, -0.03, 0.0,  -0.04, 0.03, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 1080

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.035]
landing_pos_des = [-0.02, 0.035, 0.0,  -0.02, -0.035, 0.0,  0.02, 0.035, 0.0,  0.02, -0.035, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 1080

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [-0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  0.0, 0.0, 0.0,  0.0, -0.0, 0.0]
step_height     = [0.03, 0.03, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 84
duration        = 540

# End of Trot In Out #

# Stand

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 1000

# RecoveryStand

[[step]]
type         = "recoverystand"
duration     = 1000