# Front lift

# Beginning of front lift #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.10, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, -0.03, 0.0,  0.0, 0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, 0.03, 0.0,  0.0, -0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, -0.03, 0.0,  0.0, 0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, 0.03, 0.0,  0.0, -0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.0, -0.03, 0.0,  0.0, 0.03, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 480

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
landing_pos_des = [0.05, -0.00, 0.0,  0.05, 0.00, 0.0,  0.0, 0.00, 0.0,  0.0, -0.00, 0.0]
step_height     = [0.035, 0.035, 0.02, 0.02]
weight          = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
use_mpc_traj    = 0
mu              = 0.30
landing_gain    = 1.0 
gait_id         = 81
duration        = 750

# End of front lift #

# Stand

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.10, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 1000

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 1000

# RecoveryStand

[[step]]
type         = "recoverystand"
duration     = 1000