# FR Lift

# Beginning of FR Lift #

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.08, 0.03, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 800

# 1
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.00, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.0, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.07, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.07, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [-0.04, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

# 2
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [-0.04, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.07, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.07, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [-0.04, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

# 3
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [-0.04, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.07, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, 0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.07, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [-0.04, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

# 4
[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.12, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [-0.04, -0.0, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 300

[[step]]
type            = "usergait"
body_vel_des    = [0.0, 0.0, 0.0]
body_pos_des    = [0.0, -0.0, 0.0, 0.0, 0.0, 0.025]
landing_pos_des = [0.09, -0.01, 0.0,  0.0, 0.0, 0.0,  -0.0, -0.0, 0.0,  -0.0, 0.0, 0.0]
step_height     = [0.05, 0.05, 0.03, 0.03]
weight          = [5.0, 5.0, 10.0, 10.0, 10.0, 10.0]
use_mpc_traj    = 0
mu              = 0.40
landing_gain    = 1.0 
gait_id         = 88
duration        = 240

# End of FR Lift #

# Stand

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.08, -0.03, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 500

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 31
duration     = 1000

# RecoveryStand

[[step]]
type         = "recoverystand"
duration     = 1000