# transfer body

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.33, 0.0, 0.0, 0.05, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

# step leg rf

[[step]]
type         = "pose"
foot_support = [-1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.18]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "pose"
foot_support = [-1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.15, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "pose"
foot_support = [-1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.05]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

# transfer body 

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, -0.1, 0.0]
foot_pose    = [0.0, 0.0, -0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

# step leg rf

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.18]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.15, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.03]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

#transfer body

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.15, 0.0, 0.05]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300

# step leg lb

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, -1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.07, 0.0, 0.05]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 300


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, -1.0]
body_cmd     = [0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.08, 0.0, -0.05]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 30
