# torque ctrl:   foot push ground


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, -0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 100


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.15, 0.0, 0.05, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, -1.0, 1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.01]
duration     = 10


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, -1.0, 1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.1, 0.0, 0.0]
duration     = 100


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, -1.0, 1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [-0.1, 0.0, 0.0]
duration     = 100


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, -1.0, 1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.01]
duration     = 10


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.0]
duration     = 20


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, -1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.01]
duration     = 10


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, -1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.1, 0.0, 0.0]
duration     = 100


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, -1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [-0.1, 0.0, -0.0]
duration     = 100


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, -1.0]
body_cmd     = [-0.0, -0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.01]
duration     = 10


[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.15, 0.0, -0.05, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 200



[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 3
duration     = 360
# warning: after locomotion, must add action of torctrlposture. in order  to update weight of wbc.

[[step]]
type         = "torctrlposture"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.0, -0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
duration     = 5
