#	option3:
#		jump
#		jump_foot_support
#		jump_x_acc_cmd
#		jump_w_acc_cmd
#		duration


[[step]]
type         = "transition"
height       = 0.2
duration     = 1000


[[step]]
type         = "transition"
height       = 0.10
duration     = 200


[[step]]
type         = "jump"
foot_support = [1.0, 1.0, 1.0, 1.0]
x_acc_cmd    = [10.0, 0.0, 25.0]
w_acc_cmd    = [0.0, 0.0, 0.0]
duration     = 1000


[[step]]
type         = "transition"
height       = 0.2
duration     = 1000



