#	option1:
#		locomotion
#		xdot,ydot,yawdot
#		omni
#		gait 2:四足小跳
#		duration
#
#	option2:
#		pose
#		contact state
#		pose_body_cmd roll/pitch
#		pose_foot_cmd
#		pose_ctrl_point
#		duration
#	option3:
#		jump
#		jump_foot_support
#		jump_x_acc_cmd
#		jump_w_acc_cmd
#		duration
#	option4:
#		transition
#		height
#		duration
# only be used to swingleg of three-legs support
#	option5:
#		swingleg
#		contact state
#		pose_body_cmd
#		pose_foot_cmd
#		pose_ctrl_point
#		duration
# torque controller : WBC , display posture
#	option6:
#		torctrlposture
#		contact state
#		pose_body_cmd
#		pose_foot_cmd
#		duration

# 场景3 跳舞
# #1 bounding  2 pronking   3 slowtrot  4 trot 5 trotRunning   6 walking 7  ramdom2  8 pace  9 trot  10 specialtrot  11 specialpronk

[[step]]
type         = "transition"
height       = 0.3
duration     = 1000

# 第一个八拍 原地pronk  加入交叉腿

[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 50
duration     = 2625


[[step]]
type         = "transition"
height       = 0.3
duration     = 375


[[step]]
type         = "locomotion"
vel_des      = [0.0, 0.0, 0.0]
omni         = 0
gait_id      = 7
duration     = 2625


[[step]]
type         = "transition"
height       = 0.3
duration     = 375


# 第二个八拍 抬头低头2拍

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.4, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.8, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.8, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.4, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375

# 左晃1拍  右晃1拍

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.35, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.7, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.7, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.35, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 375

# 前后跳 1拍
#jump
#1,1,1,1
#3,0,10
#0,0,0
#375

#jump
#1,1,1,1
#-3,0,10
#0,0,0
#375

#jump
#1,1,1,1
#3,0,10
#0,0,0
#375

#jump
#1,1,1,1
#-3,0,10
#0,0,0
#375


# 左转跳 1拍 右转跳 1拍
#jump
#1,1,1,1
#0,0,10
#0,0,-10
#375

#jump
#1,1,1,1
#0,0,10
#0,0,10
#375

#jump
#1,1,1,1
#0,0,10
#0,0,10
#375

#jump
#1,1,1,1
#0,0,10
#0,0,-10
#375


# 第三个八拍 正反扭屁股各两拍  模拟圆形轨迹  左右扭身体抬前腿击掌2拍

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 108


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.04, -0.004, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.038, -0.012, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.035, -0.019, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.031, -0.026, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.025, -0.031, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.018, -0.036, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.011, -0.038, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.003, -0.04, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.005, -0.04, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.013, -0.038, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02, -0.034, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.027, -0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.032, -0.024, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.036, -0.017, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.039, -0.01, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.04, -0.002, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.039, 0.006, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.037, 0.014, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.034, 0.021, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.029, 0.027, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.023, 0.033, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.016, 0.037, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.008, 0.039, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.04, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.007, 0.039, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.015, 0.037, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.022, 0.033, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.028, 0.028, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.033, 0.022, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.037, 0.015, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.039, 0.007, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30



[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.017, 0.001, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 208


# 反方向转屁股 二拍

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 108


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.04, -0.004, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.038, -0.012, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.035, -0.019, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.031, -0.026, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.025, -0.031, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.018, -0.036, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.011, -0.038, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.003, -0.04, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.005, -0.04, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.013, -0.038, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02, -0.034, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.027, -0.03, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.032, -0.024, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.036, -0.017, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.039, -0.01, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.04, -0.002, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.039, 0.006, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.037, 0.014, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.034, 0.021, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.029, 0.027, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.023, 0.033, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.016, 0.037, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 40


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.008, 0.039, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.04, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.007, 0.039, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.015, 0.037, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.022, 0.033, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.028, 0.028, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.033, 0.022, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.037, 0.015, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.039, 0.007, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.016, 0.001, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 30


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.2, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = 208


# 四小拍抬腿晃身握手


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.1, 0.4, 0.0, -0.08, -0.05, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 400


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.3, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 100


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.6, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200



[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.3, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 100


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.02]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 100


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.3, 0.0, 0.26]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 100



[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200



[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200



[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 100


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [-0.3, 0.0, -0.24]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200


[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_pose    = [0.0, 0.0, -0.04]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 200


[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.1, -0.4, 0.0, 0.08, 0.05, 0.0]
foot_pose    = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = 400


[[step]]
type         = "transition"
height       = 0.3
duration     = 1200

